# Generated by Django 4.2.3 on 2023-08-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_chess", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
